'use client';
import {useEffect,useState} from 'react';
import {Plus,Edit3,Trash2,Save,Eye,X,WalletCards,Wrench,Receipt,CheckCircle} from 'lucide-react';
import {supabase} from '@/lib/supabase-browser';

type Unit={id:string;unit_number:string;occupant_count:number;owner_name:string|null};
type RepairUnit={id:string;unit_id:string;share_amount:number;units?:{unit_number:string}|null};
const money=(n:number)=>new Intl.NumberFormat('fa-IR').format(Number(n)||0);
const today=()=>new Date().toISOString().slice(0,10);
const fmt=(v:string|null)=>v?new Date(v+'T00:00:00').toLocaleDateString('fa-IR'):'';
const emptyCharge={title:'',period:'',due_date:'',total_amount:'',allocation_method:'unit',status:'issued'};
const emptyExpense={title:'',category:'',amount:'',expense_date:'',description:''};
const emptyRepair={title:'',description:'',status:'open',total_cost:'',repair_date:''};

function Msg({text,onClose}:{text:string;onClose:()=>void}){return <div className="auth-error page-error">{text}<button onClick={onClose}><X size={15}/></button></div>}
function Head({title,sub}:{title:string;sub:string}){return <div className="panel-head"><div><h3>{title}</h3><span>{sub}</span></div></div>}
function Field({label,value,onChange,type='text',placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function FileField({label,file,onChange}:{label:string;file:File|null;onChange:(f:File|null)=>void}){return <label className="field"><span>{label}</span><input type="file" accept="image/*,.pdf" onChange={e=>onChange(e.target.files?.[0]||null)}/>{file&&<small>{file.name}</small>}</label>}
async function uploadFile(building:string,file:File,kind:string){const safe=file.name.replace(/[^\w.\-\u0600-\u06ff ]/g,'_');const path=`${building}/${kind}/${crypto.randomUUID()}-${safe}`;const{error}=await supabase.storage.from('building-files').upload(path,file,{upsert:false});if(error)throw error;return path}
async function openFile(path:string){const{data,error}=await supabase.storage.from('building-files').createSignedUrl(path,3600);if(error)throw error;if(data?.signedUrl)window.open(data.signedUrl,'_blank','noopener,noreferrer')}

export function FinanceManager({building,units,setErr}:{building:string;units:Unit[];setErr:(s:string)=>void}){
 const[charges,setCharges]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[show,setShow]=useState(false),[edit,setEdit]=useState<any>(null),[form,setForm]=useState<any>(emptyCharge),[payFor,setPayFor]=useState<any>(null),[payEdit,setPayEdit]=useState<any>(null),[receipt,setReceipt]=useState<File|null>(null),[msg,setMsg]=useState('');
 const load=async()=>{const c=await supabase.from('charges').select('*,charge_items(id,unit_id,amount,paid_amount,units(unit_number))').eq('building_id',building).order('created_at',{ascending:false});if(c.error)setErr(c.error.message);else setCharges(c.data||[]);const p=await supabase.from('payments').select('*').eq('building_id',building).order('payment_date',{ascending:false});if(p.error)setErr(p.error.message);else setPayments(p.data||[])};
 useEffect(()=>{if(building)load()},[building]);
 const closePay=()=>{setPayFor(null);setPayEdit(null);setReceipt(null);setForm(emptyCharge)};
 const saveCharge=async()=>{try{const total=Number(form.total_amount);if(!form.title.trim()||total<=0)throw new Error('عنوان و مبلغ شارژ را کامل کنید.');const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid)throw new Error('نشست کاربر معتبر نیست.');let id=edit?.id;if(edit){const old=await supabase.from('charge_items').select('id,paid_amount').eq('charge_id',id);if(old.error)throw old.error;if((old.data||[]).some((x:any)=>Number(x.paid_amount)>0))throw new Error('شارژی که پرداخت ثبت‌شده دارد قابل بازتخصیص نیست. ابتدا پرداخت‌ها را اصلاح کنید.');const r=await supabase.from('charges').update({title:form.title.trim(),period:form.period.trim()||null,due_date:form.due_date||null,total_amount:total,allocation_method:form.allocation_method,status:form.status}).eq('id',id);if(r.error)throw r.error;const d=await supabase.from('charge_items').delete().eq('charge_id',id);if(d.error)throw d.error}else{const r=await supabase.from('charges').insert({building_id:building,title:form.title.trim(),period:form.period.trim()||null,due_date:form.due_date||null,total_amount:total,allocation_method:form.allocation_method,status:form.status,created_by:uid}).select('id').single();if(r.error)throw r.error;id=r.data.id}const weights=units.map(u=>form.allocation_method==='occupants'?Math.max(1,Number(u.occupant_count)||1):1);const sum=weights.reduce((a,b)=>a+b,0);if(units.length&&sum){const items=units.map((u,i)=>({charge_id:id,unit_id:u.id,amount:Math.round(total*weights[i]/sum),paid_amount:0}));const r=await supabase.from('charge_items').insert(items);if(r.error)throw r.error}setShow(false);setEdit(null);setForm(emptyCharge);await load()}catch(e:any){setMsg(e.message||'خطا در ثبت شارژ')}};
 const removeCharge=async(id:string)=>{if(!confirm('این شارژ حذف شود؟'))return;const r=await supabase.from('charges').delete().eq('id',id);if(r.error)setMsg(r.error.message);else await load()};
 const savePayment=async()=>{try{const amount=Number(form.total_amount);if(!payFor||amount<=0)throw new Error('مبلغ پرداخت را وارد کنید.');const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid)throw new Error('نشست کاربر معتبر نیست.');let path=payEdit?.receipt_url||null;if(receipt)path=await uploadFile(building,receipt,'payments');const payload={building_id:building,unit_id:payFor.unit_id||null,charge_id:payFor.charge_id||null,repair_id:payFor.repair_id||null,amount,payment_date:form.due_date||today(),method:form.method||'manual',reference:form.reference?.trim()||null,receipt_url:path,created_by:uid};if(payEdit){const r=await supabase.from('payments').update(payload).eq('id',payEdit.id);if(r.error)throw r.error}else{const r=await supabase.from('payments').insert(payload);if(r.error)throw r.error;if(payFor.charge_item_id){const item=charges.flatMap(c=>c.charge_items||[]).find((x:any)=>x.id===payFor.charge_item_id);if(item){const next=Math.min(Number(item.amount),Number(item.paid_amount||0)+amount);const q=await supabase.from('charge_items').update({paid_amount:next}).eq('id',item.id);if(q.error)throw q.error}}}closePay();await load()}catch(e:any){setMsg(e.message||'خطا در ثبت پرداخت')}};
 const removePayment=async(p:any)=>{if(!confirm('این پرداخت حذف شود؟'))return;const r=await supabase.from('payments').delete().eq('id',p.id);if(r.error){setMsg(r.error.message);return}if(p.charge_id&&p.unit_id){const item=charges.flatMap(c=>c.charge_items||[]).find((x:any)=>x.unit_id===p.unit_id&&x.charge_id===p.charge_id);if(item)await supabase.from('charge_items').update({paid_amount:Math.max(0,Number(item.paid_amount||0)-Number(p.amount||0))}).eq('id',item.id)}await load()};
 const startChargePayment=(i:any,c:any)=>{setPayEdit(null);setReceipt(null);setPayFor({charge_item_id:i.id,unit_id:i.unit_id,charge_id:c.id,unit_number:i.units?.unit_number||'—'});setForm({total_amount:String(Math.max(0,Number(i.amount)-Number(i.paid_amount||0))),due_date:today(),method:'manual',reference:''})};
 const startPaymentEdit=(p:any)=>{const item=p.charge_id?charges.flatMap(c=>c.charge_items||[]).find((x:any)=>x.unit_id===p.unit_id&&x.charge_id===p.charge_id):null;setPayEdit(p);setReceipt(null);setPayFor({charge_item_id:item?.id,unit_id:p.unit_id,charge_id:p.charge_id,repair_id:p.repair_id,unit_number:item?.units?.unit_number||'—'});setForm({total_amount:String(p.amount),due_date:p.payment_date||today(),method:p.method||'manual',reference:p.reference||''})};
 return <div className="panel"><Head title="شارژ و پرداخت‌ها" sub="ثبت، ویرایش، حذف، تقسیم سهم، پرداخت و بارگذاری فیش."/><div className="action-row"><button className="primary" onClick={()=>{setEdit(null);setForm(emptyCharge);setShow(true)}}><Plus size={16}/> افزودن شارژ</button></div>{msg&&<Msg text={msg} onClose={()=>setMsg('')}/>} {show&&<div className="panel" style={{marginTop:16}}><div className="panel-head"><h3>{edit?'ویرایش شارژ':'شارژ جدید'}</h3><button className="secondary" onClick={()=>setShow(false)}>انصراف</button></div><div className="form-grid"><Field label="عنوان شارژ" value={form.title} onChange={v=>setForm({...form,title:v})}/><Field label="دوره" value={form.period} onChange={v=>setForm({...form,period:v})} placeholder="مثلاً شهریور ۱۴۰۵"/><Field label="تاریخ سررسید" value={form.due_date} onChange={v=>setForm({...form,due_date:v})} type="date"/><Field label="مبلغ کل" value={form.total_amount} onChange={v=>setForm({...form,total_amount:v.replace(/\D/g,'')})} type="number"/><label className="field"><span>روش تقسیم</span><select value={form.allocation_method} onChange={e=>setForm({...form,allocation_method:e.target.value})}><option value="unit">مساوی بین واحدها</option><option value="occupants">بر اساس تعداد ساکنان</option></select></label><label className="field"><span>وضعیت</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">پیش‌نویس</option><option value="issued">صادر شده</option><option value="closed">بسته شده</option></select></label></div><button className="primary dark" onClick={saveCharge}><Save size={16}/> ذخیره شارژ</button></div>}
 {payFor&&<div className="panel" style={{marginTop:16}}><div className="panel-head"><h3>{payEdit?'ویرایش پرداخت':'ثبت پرداخت'} {payFor.unit_number&&`واحد ${payFor.unit_number}`}</h3><button className="secondary" onClick={closePay}>انصراف</button></div><div className="form-grid"><Field label="مبلغ پرداخت" value={form.total_amount||''} onChange={v=>setForm({...form,total_amount:v.replace(/\D/g,'')})} type="number"/><Field label="تاریخ پرداخت" value={form.due_date||''} onChange={v=>setForm({...form,due_date:v})} type="date"/><Field label="شماره پیگیری" value={form.reference||''} onChange={v=>setForm({...form,reference:v})}/><label className="field"><span>روش پرداخت</span><select value={form.method||'manual'} onChange={e=>setForm({...form,method:e.target.value})}><option value="manual">دستی</option><option value="bank">کارت به کارت / بانکی</option><option value="cash">نقدی</option></select></label><FileField label="فیش/رسید پرداخت" file={receipt} onChange={setReceipt}/></div><button className="primary dark" onClick={savePayment}>{payEdit?'ذخیره تغییرات':'ثبت پرداخت'}</button></div>}
 <div style={{marginTop:18}}>{charges.map(c=><div className="building-row" key={c.id}><div className="building-icon"><WalletCards size={18}/></div><div className="row-main"><b>{c.title}</b><span>{c.period||'بدون دوره'} · {money(c.total_amount)} تومان · سررسید {fmt(c.due_date)}</span></div><button className="icon-btn" onClick={()=>{setEdit(c);setForm({title:c.title,period:c.period||'',due_date:c.due_date||'',total_amount:String(c.total_amount),allocation_method:c.allocation_method,status:c.status});setShow(true)}}><Edit3 size={15}/></button><button className="danger-btn" onClick={()=>removeCharge(c.id)}><Trash2 size={14}/></button></div>)}{charges.length===0&&<div className="empty-state">هنوز شارژی ثبت نشده است.</div>}</div>
 <div className="panel" style={{marginTop:16}}><Head title="پرداخت از سهم واحدها" sub="برای هر واحد، مانده سهم را ببینید و پرداخت ثبت کنید."/>{charges.flatMap(c=>(c.charge_items||[]).map((i:any)=>({...i,charge_title:c.title,charge_id:c.id}))).map((i:any)=><div className="building-row" key={i.id}><div className="row-main"><b>واحد {i.units?.unit_number||'—'}</b><span>{i.charge_title} · سهم {money(i.amount)} · پرداخت‌شده {money(i.paid_amount||0)}</span></div>{Number(i.paid_amount||0)<Number(i.amount)&&<button className="primary" onClick={()=>startChargePayment(i,{id:i.charge_id})}>پرداخت</button>}</div>)}</div>
 <div className="panel" style={{marginTop:16}}><Head title="پرداخت‌ها" sub="همه پرداخت‌های این ساختمان؛ ویرایش، حذف و مشاهده فیش."/>{payments.length===0?<div className="empty-state">هنوز پرداختی ثبت نشده است.</div>:payments.map(p=><div className="building-row" key={p.id}><div className="building-icon"><CheckCircle size={18}/></div><div className="row-main"><b>{money(p.amount)} تومان</b><span>{fmt(p.payment_date)} · {p.reference||p.method||'دستی'} {p.repair_id?' · تعمیرات':''}</span></div>{p.receipt_url&&<button className="icon-btn" onClick={()=>openFile(p.receipt_url).catch(e=>setMsg(e.message))}><Eye size={15}/> فیش</button>}<button className="icon-btn" onClick={()=>startPaymentEdit(p)}><Edit3 size={15}/></button><button className="danger-btn" onClick={()=>removePayment(p)}><Trash2 size={14}/></button></div>)}</div></div>
}

export function ExpensesManager({building,setErr}:{building:string;setErr:(s:string)=>void}){
 const[rows,setRows]=useState<any[]>([]),[show,setShow]=useState(false),[edit,setEdit]=useState<any>(null),[file,setFile]=useState<File|null>(null),[msg,setMsg]=useState(''),[f,setF]=useState<any>(emptyExpense);
 const load=async()=>{const r=await supabase.from('expenses').select('*').eq('building_id',building).order('expense_date',{ascending:false});if(r.error)setErr(r.error.message);else setRows(r.data||[])};useEffect(()=>{if(building)load()},[building]);
 const save=async()=>{try{if(!f.title.trim()||Number(f.amount)<=0)throw new Error('عنوان و مبلغ هزینه را کامل کنید.');let path=edit?.receipt_url||null;if(file)path=await uploadFile(building,file,'expenses');const uid=(await supabase.auth.getUser()).data.user?.id;const data={title:f.title.trim(),category:f.category.trim()||null,amount:Number(f.amount),expense_date:f.expense_date||today(),description:f.description.trim()||null,receipt_url:path};const r=edit?await supabase.from('expenses').update(data).eq('id',edit.id):await supabase.from('expenses').insert({...data,building_id:building,created_by:uid});if(r.error)throw r.error;setShow(false);setEdit(null);setFile(null);setF(emptyExpense);await load()}catch(e:any){setMsg(e.message||'خطا در ثبت هزینه')}};
 const remove=async(id:string)=>{if(!confirm('این هزینه حذف شود؟'))return;const r=await supabase.from('expenses').delete().eq('id',id);if(r.error)setMsg(r.error.message);else await load()};
 return <div className="panel"><Head title="هزینه‌ها" sub="ثبت، ویرایش، حذف و بارگذاری تصویر قبض یا رسید."/><div className="action-row"><button className="primary" onClick={()=>{setEdit(null);setFile(null);setF(emptyExpense);setShow(true)}}><Plus size={16}/> افزودن هزینه</button></div>{msg&&<Msg text={msg} onClose={()=>setMsg('')}/>} {show&&<div className="panel" style={{marginTop:16}}><div className="panel-head"><h3>{edit?'ویرایش هزینه':'هزینه جدید'}</h3><button className="secondary" onClick={()=>setShow(false)}>انصراف</button></div><div className="form-grid"><Field label="عنوان" value={f.title} onChange={v=>setF({...f,title:v})}/><Field label="دسته‌بندی" value={f.category} onChange={v=>setF({...f,category:v})}/><Field label="مبلغ" value={f.amount} onChange={v=>setF({...f,amount:v.replace(/\D/g,'')})} type="number"/><Field label="تاریخ هزینه" value={f.expense_date} onChange={v=>setF({...f,expense_date:v})} type="date"/><Field label="توضیحات" value={f.description} onChange={v=>setF({...f,description:v})}/><FileField label="قبض/رسید" file={file} onChange={setFile}/></div><button className="primary dark" onClick={save}><Save size={16}/> ذخیره هزینه</button></div>}{rows.map(r=><div className="building-row" key={r.id}><div className="building-icon"><Receipt size={18}/></div><div className="row-main"><b>{r.title}</b><span>{money(r.amount)} تومان · {fmt(r.expense_date)} · {r.category||'بدون دسته‌بندی'}</span></div>{r.receipt_url&&<button className="icon-btn" onClick={()=>openFile(r.receipt_url).catch(e=>setMsg(e.message))}><Eye size={15}/> رسید</button>}<button className="icon-btn" onClick={()=>{setEdit(r);setFile(null);setF({title:r.title,category:r.category||'',amount:String(r.amount),expense_date:r.expense_date||'',description:r.description||''});setShow(true)}}><Edit3 size={15}/></button><button className="danger-btn" onClick={()=>remove(r.id)}><Trash2 size={14}/></button></div>)}{rows.length===0&&<div className="empty-state">هنوز هزینه‌ای ثبت نشده است.</div>}</div>
}

export function RepairsManager({building,units,setErr}:{building:string;units:Unit[];setErr:(s:string)=>void}){
 const[rows,setRows]=useState<any[]>([]),[show,setShow]=useState(false),[edit,setEdit]=useState<any>(null),[file,setFile]=useState<File|null>(null),[msg,setMsg]=useState(''),[f,setF]=useState<any>(emptyRepair),[selected,setSelected]=useState<string[]>([]),[shares,setShares]=useState<Record<string,string>>({}),[repairPayments,setRepairPayments]=useState<any[]>([]),[pay,setPay]=useState<any>(null),[payFile,setPayFile]=useState<File|null>(null),[payForm,setPayForm]=useState<any>({amount:'',date:today(),reference:'',method:'manual'});
 const load=async()=>{const r=await supabase.from('repairs').select('*,repair_units(id,unit_id,share_amount,units(unit_number))').eq('building_id',building).order('repair_date',{ascending:false});if(r.error)setErr(r.error.message);else setRows(r.data||[]);const p=await supabase.from('payments').select('*').eq('building_id',building).not('repair_id','is',null).order('payment_date',{ascending:false});if(p.error)setErr(p.error.message);else setRepairPayments(p.data||[])};useEffect(()=>{if(building)load()},[building]);
 const reset=()=>{setShow(false);setEdit(null);setFile(null);setF(emptyRepair);setSelected([]);setShares({})};
 const save=async()=>{try{if(!f.title.trim()||Number(f.total_cost)<=0)throw new Error('عنوان و مبلغ تعمیرات را کامل کنید.');const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid)throw new Error('نشست کاربر معتبر نیست.');let id=edit?.id;const data={title:f.title.trim(),description:f.description.trim()||null,status:f.status,total_cost:Number(f.total_cost),repair_date:f.repair_date||today(),receipt_url:edit?.receipt_url||null};if(file)data.receipt_url=await uploadFile(building,file,'repairs');if(edit){const r=await supabase.from('repairs').update(data).eq('id',id);if(r.error)throw r.error;const d=await supabase.from('repair_units').delete().eq('repair_id',id);if(d.error)throw d.error}else{const r=await supabase.from('repairs').insert({...data,building_id:building,created_by:uid}).select('id').single();if(r.error)throw r.error;id=r.data.id}if(selected.length){const total=Number(f.total_cost);const vals=selected.map(u=>Number(shares[u]||0));const hasAny=vals.some(v=>v>0);const sum=vals.reduce((a,b)=>a+b,0);const items=selected.map((u,i)=>({repair_id:id,unit_id:u,share_amount:hasAny?Number(shares[u]||0):Math.round(total/selected.length)}));if(hasAny&&Math.abs(sum-total)>1)throw new Error('جمع سهم واحدها باید برابر مبلغ کل تعمیرات باشد.');const r=await supabase.from('repair_units').insert(items);if(r.error)throw r.error}reset();await load()}catch(e:any){setMsg(e.message||'خطا در ثبت تعمیرات')}};
 const remove=async(id:string)=>{if(!confirm('این تعمیرات حذف شود؟'))return;const r=await supabase.from('repairs').delete().eq('id',id);if(r.error)setMsg(r.error.message);else await load()};
 const startEdit=(r:any)=>{const ru=(r.repair_units||[]) as RepairUnit[];setEdit(r);setF({title:r.title,description:r.description||'',status:r.status||'open',total_cost:String(r.total_cost),repair_date:r.repair_date||''});setSelected(ru.map(x=>x.unit_id));setShares(Object.fromEntries(ru.map(x=>[x.unit_id,String(x.share_amount)])));setFile(null);setShow(true)};
 const savePayment=async()=>{try{if(!pay||Number(payForm.amount)<=0)throw new Error('مبلغ پرداخت را وارد کنید.');const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid)throw new Error('نشست کاربر معتبر نیست.');let path=pay?.receipt_url||null;if(payFile)path=await uploadFile(building,payFile,'payments');const r=await supabase.from('payments').insert({building_id:building,unit_id:pay.unit_id,repair_id:pay.repair_id,charge_id:null,amount:Number(payForm.amount),payment_date:payForm.date||today(),method:payForm.method||'manual',reference:payForm.reference.trim()||null,receipt_url:path,created_by:uid});if(r.error)throw r.error;setPay(null);setPayFile(null);setPayForm({amount:'',date:today(),reference:'',method:'manual'});await load()}catch(e:any){setMsg(e.message||'خطا در ثبت پرداخت تعمیرات')}};
 const removePayment=async(p:any)=>{if(!confirm('این پرداخت تعمیرات حذف شود؟'))return;const r=await supabase.from('payments').delete().eq('id',p.id);if(r.error)setMsg(r.error.message);else await load()};
 return <div className="panel"><Head title="تعمیرات" sub="ثبت، ویرایش، حذف، انتخاب واحدهای مشمول، سهم هر واحد، تصویر قبض و پرداخت تعمیرات."/><div className="action-row"><button className="primary" onClick={()=>{setEdit(null);setFile(null);setF(emptyRepair);setSelected([]);setShares({});setShow(true)}}><Plus size={16}/> افزودن تعمیرات</button></div>{msg&&<Msg text={msg} onClose={()=>setMsg('')}/>} {show&&<div className="panel" style={{marginTop:16}}><div className="panel-head"><h3>{edit?'ویرایش تعمیرات':'تعمیرات جدید'}</h3><button className="secondary" onClick={reset}>انصراف</button></div><div className="form-grid"><Field label="عنوان تعمیرات" value={f.title} onChange={v=>setF({...f,title:v})}/><Field label="مبلغ کل" value={f.total_cost} onChange={v=>setF({...f,total_cost:v.replace(/\D/g,'')})} type="number"/><Field label="تاریخ" value={f.repair_date} onChange={v=>setF({...f,repair_date:v})} type="date"/><Field label="توضیحات" value={f.description} onChange={v=>setF({...f,description:v})}/><label className="field"><span>وضعیت</span><select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option value="open">در حال بررسی</option><option value="in_progress">در حال انجام</option><option value="completed">انجام شده</option><option value="cancelled">لغو شده</option></select></label><FileField label="قبض/فاکتور تعمیرات" file={file} onChange={setFile}/></div><div className="panel" style={{marginTop:12}}><div className="panel-head"><div><h3>واحدهای مشمول</h3><span>واحدها را انتخاب کنید. اگر سهمی وارد نکنید، مبلغ مساوی تقسیم می‌شود.</span></div></div>{units.length===0?<div className="empty-state">واحدی برای انتخاب وجود ندارد.</div>:units.map(u=><div className="building-row" key={u.id}><label style={{display:'flex',alignItems:'center',gap:10,flex:1}}><input type="checkbox" checked={selected.includes(u.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,u.id]:v.filter(x=>x!==u.id))}/><b>واحد {u.unit_number}</b></label>{selected.includes(u.id)&&<input className="field" style={{maxWidth:180}} placeholder="سهم (تومان)" value={shares[u.id]||''} onChange={e=>setShares(v=>({...v,[u.id]:e.target.value.replace(/\D/g,'')}))}/>}</div>)}</div><button className="primary dark" onClick={save}><Save size={16}/> ذخیره تعمیرات</button></div>}
 {rows.map(r=><div className="building-row" key={r.id}><div className="building-icon"><Wrench size={18}/></div><div className="row-main"><b>{r.title}</b><span>{money(r.total_cost)} تومان · {fmt(r.repair_date)} · {r.repair_units?.length||0} واحد</span></div>{r.receipt_url&&<button className="icon-btn" onClick={()=>openFile(r.receipt_url).catch(e=>setMsg(e.message))}><Eye size={15}/> فاکتور</button>}<button className="icon-btn" onClick={()=>{const ru=(r.repair_units||[]);const target=ru[0];if(target){setPay({repair_id:r.id,unit_id:target.unit_id,unit_number:target.units?.unit_number||'—'});setPayForm({amount:String(Math.max(0,Number(target.share_amount)||0)),date:today(),reference:'',method:'manual'});setPayFile(null)}else setMsg('ابتدا برای تعمیرات حداقل یک واحد مشمول انتخاب کنید.')}}>پرداخت</button><button className="icon-btn" onClick={()=>startEdit(r)}><Edit3 size={15}/></button><button className="danger-btn" onClick={()=>remove(r.id)}><Trash2 size={14}/></button></div>)}{rows.length===0&&<div className="empty-state">هنوز تعمیراتی ثبت نشده است.</div>}
 {pay&&<div className="panel" style={{marginTop:16}}><div className="panel-head"><h3>ثبت پرداخت تعمیرات · واحد {pay.unit_number}</h3><button className="secondary" onClick={()=>setPay(null)}>انصراف</button></div><div className="form-grid"><Field label="مبلغ پرداخت" value={payForm.amount} onChange={v=>setPayForm({...payForm,amount:v.replace(/\D/g,'')})} type="number"/><Field label="تاریخ پرداخت" value={payForm.date} onChange={v=>setPayForm({...payForm,date:v})} type="date"/><Field label="شماره پیگیری" value={payForm.reference} onChange={v=>setPayForm({...payForm,reference:v})}/><label className="field"><span>روش پرداخت</span><select value={payForm.method} onChange={e=>setPayForm({...payForm,method:e.target.value})}><option value="manual">دستی</option><option value="bank">بانکی</option><option value="cash">نقدی</option></select></label><FileField label="فیش پرداخت" file={payFile} onChange={setPayFile}/></div><button className="primary dark" onClick={savePayment}>ثبت پرداخت</button></div>}
 <div className="panel" style={{marginTop:16}}><Head title="پرداخت‌های تعمیرات" sub="پرداخت‌های ثبت‌شده مربوط به تعمیرات."/>{repairPayments.length===0?<div className="empty-state">هنوز پرداخت تعمیراتی ثبت نشده است.</div>:repairPayments.map(p=><div className="building-row" key={p.id}><div className="row-main"><b>{money(p.amount)} تومان</b><span>{fmt(p.payment_date)} · واحد {units.find(u=>u.id===p.unit_id)?.unit_number||'—'} · {p.reference||p.method||'دستی'}</span></div>{p.receipt_url&&<button className="icon-btn" onClick={()=>openFile(p.receipt_url).catch(e=>setMsg(e.message))}><Eye size={15}/> فیش</button>}<button className="danger-btn" onClick={()=>removePayment(p)}><Trash2 size={14}/></button></div>)}</div></div>
}
