'use client';
import {useEffect,useState} from 'react';
import {Edit3,Trash2,Upload,Eye,Save,X} from 'lucide-react';
import {supabase} from '@/lib/supabase-browser';

type Unit={id:string;unit_number:string};
type Pay={id:string;building_id:string;unit_id:string|null;charge_id:string|null;repair_id:string|null;amount:number;payment_date:string;method:string|null;reference_no:string|null;receipt_url:string|null;notes:string|null;unit?:{unit_number:string}|null;};
const methods=['کارت به کارت','واریز بانکی','نقدی','درگاه','سایر'];
export function PaymentManagement({building,units,setErr}:{building:string;units:Unit[];setErr:(s:string)=>void}){
 const [rows,setRows]=useState<Pay[]>([]); const [charges,setCharges]=useState<any[]>([]); const [repairs,setRepairs]=useState<any[]>([]); const [edit,setEdit]=useState<Pay|null>(null); const [form,setForm]=useState<any>({unit_id:'',charge_id:'',repair_id:'',amount:'',payment_date:new Date().toISOString().slice(0,10),method:'کارت به کارت',reference_no:'',notes:''}); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false);
 const load=async()=>{if(!building)return; const [{data:p,error:pe},{data:c,error:ce},{data:r,error:re}]=await Promise.all([supabase.from('payments').select('*,unit:units(unit_number)').eq('building_id',building).order('payment_date',{ascending:false}).order('created_at',{ascending:false}),supabase.from('charges').select('id,title,period').eq('building_id',building).order('created_at',{ascending:false}),supabase.from('repairs').select('id,title').eq('building_id',building).order('repair_date',{ascending:false})]); if(pe) setErr(pe.message); if(ce)setErr(ce.message); if(re)setErr(re.message); setRows((p||[]) as Pay[]);setCharges(c||[]);setRepairs(r||[])};
 useEffect(()=>{load()},[building]);
 const recalc=async(chargeId:string|null,unitId:string|null)=>{if(!chargeId||!unitId)return; const {data}=await supabase.from('payments').select('amount').eq('charge_id',chargeId).eq('unit_id',unitId); const total=(data||[]).reduce((s:number,p:any)=>s+Number(p.amount||0),0); await supabase.from('charge_items').update({paid_amount:total}).eq('charge_id',chargeId).eq('unit_id',unitId)};
 const save=async()=>{if(!edit||!form.amount)return;setBusy(true);let receipt=edit.receipt_url; try{if(file){const path=`${building}/payments/${edit.id}-${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await supabase.storage.from('building-files').upload(path,file,{upsert:true});if(error)throw error;receipt=path;}
  const old={charge_id:edit.charge_id,unit_id:edit.unit_id}; const {error}=await supabase.from('payments').update({unit_id:form.unit_id||null,charge_id:form.charge_id||null,repair_id:form.repair_id||null,amount:Number(form.amount),payment_date:form.payment_date,method:form.method,reference_no:form.reference_no||null,notes:form.notes||null,receipt_url:receipt}).eq('id',edit.id); if(error)throw error; await recalc(old.charge_id,old.unit_id); await recalc(form.charge_id||null,form.unit_id||null); setEdit(null);setFile(null);await load();
 }catch(e:any){setErr(e.message||'خطا در ذخیره پرداخت')}finally{setBusy(false)}};
 const remove=async(p:Pay)=>{if(!confirm('این پرداخت حذف شود؟'))return; const {error}=await supabase.from('payments').delete().eq('id',p.id);if(error){setErr(error.message);return}await recalc(p.charge_id,p.unit_id);await load()};
 const view=async(path:string|null)=>{if(!path)return;const {data,error}=await supabase.storage.from('building-files').createSignedUrl(path,3600);if(error)setErr(error.message);else if(data?.signedUrl)window.open(data.signedUrl,'_blank','noopener,noreferrer')};
 const start=(p:Pay)=>{setEdit(p);setForm({unit_id:p.unit_id||'',charge_id:p.charge_id||'',repair_id:p.repair_id||'',amount:p.amount,payment_date:p.payment_date,method:p.method||'سایر',reference_no:p.reference_no||'',notes:p.notes||''});setFile(null)};
 return <div className="panel" style={{marginTop:16}}><div className="panel-head"><div><h3>مدیریت پرداخت‌ها</h3><span>ویرایش، حذف، رسید و اطلاعات کامل هر پرداخت</span></div></div>
 {edit&&<div className="inline-form"><div className="form-grid"><label>واحد<select value={form.unit_id} onChange={e=>setForm({...form,unit_id:e.target.value})}><option value="">انتخاب</option>{units.map(u=><option key={u.id} value={u.id}>واحد {u.unit_number}</option>)}</select></label><label>شارژ<select value={form.charge_id} onChange={e=>setForm({...form,charge_id:e.target.value})}><option value="">بدون شارژ</option>{charges.map(c=><option key={c.id} value={c.id}>{c.title} {c.period||''}</option>)}</select></label><label>تعمیرات<select value={form.repair_id} onChange={e=>setForm({...form,repair_id:e.target.value})}><option value="">بدون تعمیرات</option>{repairs.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>مبلغ<input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>تاریخ<input type="date" value={form.payment_date} onChange={e=>setForm({...form,payment_date:e.target.value})}/></label><label>روش پرداخت<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}>{methods.map(m=><option key={m}>{m}</option>)}</select></label><label>شماره پیگیری<input value={form.reference_no} onChange={e=>setForm({...form,reference_no:e.target.value})}/></label><label>رسید<input type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label style={{gridColumn:'1/-1'}}>توضیحات<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><button className="primary dark" onClick={save} disabled={busy}><Save size={15}/> ذخیره</button><button className="secondary" onClick={()=>setEdit(null)}><X size={15}/> انصراف</button></div>}
 <div className="table-wrap"><table><thead><tr><th>واحد</th><th>مبلغ</th><th>تاریخ</th><th>روش</th><th>پیگیری</th><th>رسید</th><th>عملیات</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td>{p.unit?.unit_number||'—'}</td><td>{new Intl.NumberFormat('fa-IR').format(Number(p.amount))}</td><td>{p.payment_date}</td><td>{p.method||'—'}</td><td>{p.reference_no||'—'}</td><td>{p.receipt_url?<button className="icon-btn" onClick={()=>view(p.receipt_url)}><Eye size={14}/> مشاهده</button>:'—'}</td><td><button className="icon-btn" onClick={()=>start(p)}><Edit3 size={14}/></button><button className="danger-btn" onClick={()=>remove(p)}><Trash2 size={14}/></button></td></tr>)}{!rows.length&&<tr><td colSpan={7}>پرداختی ثبت نشده است.</td></tr>}</tbody></table></div></div>
}
