'use client';
import {useEffect,useState} from 'react';
import {Edit3,Trash2,UserPlus,Save,X,Power,PowerOff} from 'lucide-react';
import {supabase} from '@/lib/supabase-browser';

type Unit={id:string;unit_number:string}; type Row={user_id:string;unit_id:string;is_primary:boolean;full_name:string|null;phone:string|null;email:string|null;};
export function ResidentsManager({building,units,setErr}:{building:string;units:Unit[];setErr:(s:string)=>void}){
 const [rows,setRows]=useState<Row[]>([]); const [edit,setEdit]=useState<Row|null>(null); const [form,setForm]=useState<any>({unit_id:'',username:'',password:'',full_name:'',phone:'',is_primary:true}); const [busy,setBusy]=useState(false);
 const load=async()=>{if(!building)return;const {data,error}=await supabase.from('unit_residents').select('user_id,unit_id,is_primary,profiles(full_name,phone),units!inner(building_id)').eq('units.building_id',building);if(error){setErr(error.message);return}const ids=(data||[]).map((r:any)=>r.user_id);let emails:any={};if(ids.length){const {data:p}=await supabase.from('profiles').select('id,full_name,phone').in('id',ids);(p||[]).forEach((x:any)=>{emails[x.id]=x})}setRows((data||[]).map((r:any)=>({user_id:r.user_id,unit_id:r.unit_id,is_primary:r.is_primary,full_name:emails[r.user_id]?.full_name||r.profiles?.full_name||null,phone:emails[r.user_id]?.phone||r.profiles?.phone||null,email:null})))};
 useEffect(()=>{load()},[building]);
 const reset=()=>{setEdit(null);setForm({unit_id:'',username:'',password:'',full_name:'',phone:'',is_primary:true})};
 const save=async()=>{if(!form.unit_id||!form.full_name){setErr('واحد و نام ساکن را وارد کنید');return}setBusy(true);try{if(!edit){if(!form.username||!form.password){setErr('نام کاربری و رمز عبور را وارد کنید');return}const {data,error}=await supabase.functions.invoke('create-resident-account',{body:{building_id:building,unit_id:form.unit_id,username:form.username,password:form.password,full_name:form.full_name,phone:form.phone,is_primary:form.is_primary}});if(error)throw error;if(data?.error)throw new Error(data.error)}else{const {data,error}=await supabase.functions.invoke('manage-resident-account',{body:{action:'update',building_id:building,user_id:edit.user_id,unit_id:form.unit_id,username:form.username||undefined,password:form.password||undefined,full_name:form.full_name,phone:form.phone,is_primary:form.is_primary}});if(error)throw error;if(data?.error)throw new Error(data.error)}reset();await load()}catch(e:any){setErr(e.message||'خطا در حساب ساکن')}finally{setBusy(false)}};
 const act=async(row:Row,action:'disable'|'enable'|'delete')=>{if(action==='delete'&&!confirm('حساب این ساکن و دسترسی او حذف شود؟'))return;const {data,error}=await supabase.functions.invoke('manage-resident-account',{body:{action,building_id:building,user_id:row.user_id}});if(error||data?.error)setErr(error?.message||data?.error||'خطا');else await load()};
 return <div className="panel" style={{marginTop:16}}><div className="panel-head"><div><h3>ساکنان و حساب‌های ورود</h3><span>مدیر می‌تواند برای هر ساکن نام کاربری و رمز بسازد و دسترسی را مدیریت کند.</span></div></div><div className="form-grid"><label>واحد<select value={form.unit_id} onChange={e=>setForm({...form,unit_id:e.target.value})}><option value="">انتخاب واحد</option>{units.map(u=><option key={u.id} value={u.id}>واحد {u.unit_number}</option>)}</select></label><label>نام کامل<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>تلفن<input inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>نام کاربری<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder={edit?'بدون تغییر':'حداقل ۳ کاراکتر'}/></label><label>رمز عبور<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder={edit?'برای تغییر وارد کنید':'حداقل ۶ کاراکتر'}/></label></div><button className="primary dark" onClick={save} disabled={busy}>{edit?<><Save size={15}/> ذخیره ویرایش</>:<><UserPlus size={15}/> ساخت حساب ساکن</>}</button>{edit&&<button className="secondary" onClick={reset}><X size={15}/> انصراف</button>}<div className="table-wrap" style={{marginTop:18}}><table><thead><tr><th>ساکن</th><th>تلفن</th><th>واحد</th><th>اصلی</th><th>عملیات</th></tr></thead><tbody>{rows.map(r=><tr key={r.user_id}><td>{r.full_name||'بدون نام'}</td><td>{r.phone||'—'}</td><td>{units.find(u=>u.id===r.unit_id)?.unit_number||'—'}</td><td>{r.is_primary?'بله':'خیر'}</td><td><button className="icon-btn" onClick={()=>{setEdit(r);setForm({unit_id:r.unit_id,username:'',password:'',full_name:r.full_name||'',phone:r.phone||'',is_primary:r.is_primary})}}><Edit3 size={14}/> ویرایش</button><button className="icon-btn" onClick={()=>act(r,'disable')}><PowerOff size={14}/> غیرفعال</button><button className="danger-btn" onClick={()=>act(r,'delete')}><Trash2 size={14}/></button></td></tr>)}{!rows.length&&<tr><td colSpan={5}>هنوز حساب ساکنی ساخته نشده است.</td></tr>}</tbody></table></div></div>
}
